plusone = $(Process) + 1
procID = $INT(plusone,%d)

executable          = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/run_cl3d_selection.sh
arguments           = pion $(procID) default
output              = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/out/pion_default_$(procID).out 
error               = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/err/pion_default_$(procID).err 
log                 = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/log/pion_default_$(procID).log
+JobFlavour         = "microcentury"
queue 379
