plusone = $(Process) + 1
procID = $INT(plusone,%d)

executable          = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/run_cl3d_selection_93X.sh
arguments           = neutrino $(procID) default
output              = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/out/neutrino_default_93X_$(procID).out 
error               = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/err/neutrino_default_93X_$(procID).err 
log                 = /afs/cern.ch/work/j/jlangfor/HGCal/L1/CMSSW_10_4_0/src/L1Trigger/analysis/run/jobs/log/neutrino_default_93X_$(procID).log
+JobFlavour         = "microcentury"
queue 623
